In [1]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.random.randint(2, 11, size=(3, 3), dtype=int)

# Convert array to float type
matrix_float = matrix.astype(float)

# Flatten the matrix to 1D
flattened_array = matrix_float.flatten()

# Find the maximum and minimum values of the flattened array
max_value = np.max(flattened_array)
min_value = np.min(flattened_array)

# Output the results
print("Original 3x3 matrix:")
print(matrix)
print("\nMatrix converted to float type:")
print(matrix_float)
print("\nFlattened array:")
print(flattened_array)
print("\nMaximum value:", max_value)
print("Minimum value:", min_value)


Original 3x3 matrix:
[[ 2  8  4]
 [ 9  7  2]
 [10  8  3]]

Matrix converted to float type:
[[ 2.  8.  4.]
 [ 9.  7.  2.]
 [10.  8.  3.]]

Flattened array:
[ 2.  8.  4.  9.  7.  2. 10.  8.  3.]

Maximum value: 10.0
Minimum value: 2.0
